name: Send Email

on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.mjum473@gmail.com}}
          password: ${{secrets.nxpq fwby micw zwf}}
          subject: NIGERIAN PRINCE WISHES YOU A MERRY CHRISTMAS
          body: Sunmarli/Harjutus_10-Email. which is owned by Sunmarli.
          to:  mjum473@gmail.com
          from: mjum473@gmail.com
